// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDliAiKeCb2PJ3XgtuBbPbDs0b3-fhH2Rs',
    appId: '1:998351090660:web:5ab4f1ff7bc78366b40df1',
    messagingSenderId: '998351090660',
    projectId: 'iotproject-6bdf3',
    authDomain: 'iotproject-6bdf3.firebaseapp.com',
    databaseURL: 'https://iotproject-6bdf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-6bdf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUktZSbQhU_uqodKRNOLwOT-BAret8CtE',
    appId: '1:998351090660:android:cc813d7f1af922e6b40df1',
    messagingSenderId: '998351090660',
    projectId: 'iotproject-6bdf3',
    databaseURL: 'https://iotproject-6bdf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-6bdf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0XNi8QOlrglOa9ekw0ju3PKR5TK5tmE',
    appId: '1:998351090660:ios:8b6990ce95b684afb40df1',
    messagingSenderId: '998351090660',
    projectId: 'iotproject-6bdf3',
    databaseURL: 'https://iotproject-6bdf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-6bdf3.firebasestorage.app',
    iosBundleId: 'com.example.bayi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ0XNi8QOlrglOa9ekw0ju3PKR5TK5tmE',
    appId: '1:998351090660:ios:8b6990ce95b684afb40df1',
    messagingSenderId: '998351090660',
    projectId: 'iotproject-6bdf3',
    databaseURL: 'https://iotproject-6bdf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-6bdf3.firebasestorage.app',
    iosBundleId: 'com.example.bayi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDliAiKeCb2PJ3XgtuBbPbDs0b3-fhH2Rs',
    appId: '1:998351090660:web:cf357ca7ba9f26a9b40df1',
    messagingSenderId: '998351090660',
    projectId: 'iotproject-6bdf3',
    authDomain: 'iotproject-6bdf3.firebaseapp.com',
    databaseURL: 'https://iotproject-6bdf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotproject-6bdf3.firebasestorage.app',
  );
}
